name:                serial-inspector
version:             0.1.0.0
github:              "AshleyYakeley/serial-inspector"
license:             BSD3
author:              "Ashley Yakeley"
maintainer:          "ashley@semantic.org"
copyright:           "2022 Ashley Yakeley"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/AshleyYakeley/serial-inspector#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
- ExistentialQuantification
- ConstraintKinds
- RankNTypes
- AllowAmbiguousTypes
- ScopedTypeVariables
- TypeApplications
- DefaultSignatures
- TypeSynonymInstances
- FlexibleInstances
- OverloadedStrings

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  serial-inspector-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - text
    # candidates
    - cereal
    - cereal-text
    - binary
    - serialise
    - winery
    - store
    - flat
