resolver: lts-20.4
packages:
- .

allow-newer: true

extra-deps:
- winery-1.4
- barbies-th-0.1.10
- fast-builder-0.1.3.0
- leb128-0.1.0.0
- git: git@github.com:AshleyYakeley/primitive-serial.git
  commit: 13d6f773dba2a05876f3c7d41780320930932baa
- git: git@github.com:AshleyYakeley/Truth.git
  commit: 9678f42b703fd1163ecb6adcf74f637adbb31939
  subdirs:
  - Changes/thread-trace
  - Changes/shapes
